### ISSUE TITLE
Main PopUp Logic 

### ISSUE THREAD

**Issue by Jeremy-Kr** [money-fragments/money-fragments-client#13]
메인 컴포넌트 내부에서 동작하는 지도 핀 팝업 로직을 작성합니다.

**Comment by harenohee** [comment]
- [x] 클릭한 위치에 마커 표시하기 - 기능: 메모추가
- [x] 장소 검색 라이브러리 추가

**Comment by harenohee** [comment]
인포윈도우에 컴포넌트를 바로 쓸 수 없는 이슈가 있어서 해결해보겠습니다.
https://devtalk.kakao.com/t/topic/105513

**Comment by Jeremy-Kr** [comment]
> 인포윈도우에 컴포넌트를 바로 쓸 수 없는 이슈가 있어서 해결해보겠습니다. https://devtalk.kakao.com/t/topic/105513

저도 좀있다 서치 한번 해볼게요~ 혹시 해결 안되면 바닐라 html로 가야겠네요

**Comment by harenohee** [comment]
> > 인포윈도우에 컴포넌트를 바로 쓸 수 없는 이슈가 있어서 해결해보겠습니다. https://devtalk.kakao.com/t/topic/105513
> 
> 저도 좀있다 서치 한번 해볼게요~ 혹시 해결 안되면 바닐라 html로 가야겠네요

넹 그래야할 것 같아요. https://react-kakao-maps-sdk.jaeseokim.dev/
 공식 라이브러리가 아니라 권고하진 않지만 하나의 대안으로 올려봅니다. 나중에 생길 이슈 생각하면 바닐라 자스로 가는게 맘 편할 수도 있겠어요..

**Comment by Jeremy-Kr** [comment]
> > > 인포윈도우에 컴포넌트를 바로 쓸 수 없는 이슈가 있어서 해결해보겠습니다. https://devtalk.kakao.com/t/topic/105513
> 
> > 
> 
> > 저도 좀있다 서치 한번 해볼게요~ 혹시 해결 안되면 바닐라 html로 가야겠네요
> 
> 
> 
> 넹 그래야할 것 같아요. https://react-kakao-maps-sdk.jaeseokim.dev/
> 
>  공식 라이브러리가 아니라 권고하진 않지만 하나의 대안으로 올려봅니다. 나중에 생길 이슈 생각하면 바닐라 자스로 가는게 맘 편할 수도 있겠어요..

넵 확인했습니다. 요고 3조에 태영님이 사용하시던데, 좀있다 오후에 저 볼일 끝나는데로 들어가 보고 있으시면 얘기 나눠볼게요

**Comment by harenohee** [comment]
결국 라이브러리 활용했습니다. 🥹

- [ ] 메모 로직 추가
